using UnityEngine;

//Player class, handles any events generated by the player
[RequireComponent(typeof(VM))]
public class Player : MonoBehaviour
{
    VM spellEngine = null;

    private void Awake()
    {
        spellEngine = GetComponent<VM>();
    }

    //Player clicked "Cast Spell" button, tell VM to process selected spell
    public void CastSpell()
    {
        spellEngine.SelectSpell(this);
    }

    //Player changed value of spell drop down menu, tell VM to create spell object from the bytecode at the given index
    public void SelectSpell(int spellIndex)
    {
        spellEngine.SetSpellIndex(spellIndex);
    }


}
